# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '00 1 * * 1'  # At 01:00 on Mondays.
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: reqs
        run: |
          python3 -m pip install -r requirements.txt
          npm install
      - name: acquire data
        run: |
          python3 bench.py
      - name: manage data
        run: |
          python3 data.py
          npm run build
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 5a4bb5a5bc7410f38fe99baf2d033fb7
          command: pages publish --project-name=python_bench
          workingDirectory: dist

